name: Setup pnpm
description: Common setup steps used by our workflows
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      run: corepack enable

    - name: Setup node
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version-file: .nvmrc
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: Install node dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
