name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read
  packages: read

jobs:
  main:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release)') }}
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        run: corepack enable

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Primitives
        run: pnpm primitives:build

      - name: Build Components
        run: pnpm components:build

      - name: Build shadcn
        run: pnpm shadcn:build

      - name: Build taxonomy
        run: pnpm showcase-taxonomy:build

      - name: Build dashboard
        run: pnpm showcase-dashboard:build

      - name: Test Primitives
        run: pnpm primitives:test

      - name: Linters
        run: |
          pnpm run prettier
          pnpm run stylelint --max-warnings=0
          pnpm run eslint --max-warnings=0
