name: Publish

on:
  push:
    tags:
      - '*@*.*.*'

permissions:
  contents: read
  packages: write
  id-token: write # needed for provenance data generation

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: ./.github/actions/setup

      - name: Print Environment Info
        run: npx nx report

      - name: Build
        run: pnpm primitives:build

      - name: Build shadcn
        run: pnpm shadcn:build

      - name: Publish package
        run: npx nx release publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#      # Workaround for https://github.com/nrwl/nx/issues/20978
#      - run: |
#          sudo apt update
#          sudo apt install -y patchutils
#          git diff HEAD~1 -- "**/package.json" | grepdiff workspace: --output-matching=hunk --only-match=removals | git apply --reverse  --unidiff-zero --allow-empty
#          if [ $(git ls-files -m "**/package.json") ]; then
#           git add "**/package.json"
#           git commit -m "publish: restore workspace dependencies [skip ci]"
#           git push
#          fi
