name: Publish

# Rules that triggers the workflows
on:
  release:
    types:
      - created

permissions:
  contents: read
  packages: write
  id-token: write # needed for provenance data generation

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - run: corepack enable

      - name: Setup pnpm
        uses: ./.github/actions/setup

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Build
        run: pnpm primitives:build

      - name: Build shadcn
        run: pnpm shadcn:build

      - name: Publish package 📦
        run: npx nx release publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
